$(document).ready(function(){
    // $("*").text("Selected all");
    // $("#test").text("Selected all");
    // $(".card").text("Selected all");
    // $(".card, .card2").text("Selected all");
    // $("h1, #test, .card2").text("Selected all");
    // $("div > span").text("Selected all");
    // $("div span").text("Selected all");
    // $("div + p").text("Selected all");
    // $("div ~ p").text("Selected all");
    // $("[class]").text("Selected all");
    // $("[id]").text("Selected all");
    // $("a[href!='jQuery.html']").text("Selected all");
    // $("a[href!='jQuery.html']").text("Selected all");
    // $("button[title^='btn']").text("Selected all");
    // $("button[title*='-btn-']").text("Selected all");
    // $("div p:first-child").text("Selected all");
    // $("p:first-of-type").text("Selected all");
    // $("p:last-child").text("Selected all");
    // $("p:last-of-type").text("Selected all");
    // $("li:nth-child(3)").text("Selected all");
    // $("li:nth-last-child(2)").text("Selected all");
    // $("p:nth-of-type(3)").text("Selected all");
    // $("p:nth-of-type(3)").text("Selected all");
    // $("p:only-child").text("Selected all");
    // $("li:eq(0)").text("Selected element");
    // $("li:gt(3)").text("Selected element");
    // $("li:lt(4)").text("Selected element");
    // $("p:not(.text-block)").text("Selected element");
    // $("div:empty, h1:empty").text("Selected element");
    // $("p:has(span)").text("Selected element");
    // $(":input").val("Selected element");
    // $(":text").val("Selected element");
    // $(":password").val("Selected element");
    // $(":radio").prop('checked', false);
    // $(":checked").prop('checked', false);
    // $(":checkbox").prop('checked', true);
    // $(":selected").text("jQuery");
    // $(":submit").text("jQuery");
    // $(":disabled").text("Disabled");


}); 